import { Column, Model, Table, HasOne, HasMany, DataType, PrimaryKey, AutoIncrement, Unique, ForeignKey, CreatedAt, UpdatedAt, DeletedAt, Default, BelongsTo } from 'sequelize-typescript';
import belongsTo from 'sequelize/types/lib/associations/belongs-to';
import { Discount } from 'src/discount/discount.model';
import { Product } from 'src/product/product.model';

@Table({
    timestamps: true,
    paranoid: true,
    tableName: 'categories'
})
export class Category extends Model<Category> {
    //main primary key
    //generated by system
    @PrimaryKey
    @AutoIncrement
    @Column
    id: number;
    
    //foreign key of wallet entity
    @ForeignKey(() => Category)
    @Column
    category_id: number;

    //foreign key of wallet entity
    @ForeignKey(() => Discount)
    @Column
    discount_id: number;

    @BelongsTo( () => Discount)
    discount: Discount;

    @Column
    title: string;

    //created at datetime
    @CreatedAt
    created_at: Date;

    //updated at datetime
    @UpdatedAt
    updated_at: Date;

    //deleted at datetime
    @DeletedAt
    deleted_at: Date;

    @HasMany( () => Product)
    products: Product;
}