import { Column, Model, Table, HasOne, HasMany, DataType, PrimaryKey, AutoIncrement, Unique, ForeignKey, CreatedAt, UpdatedAt, DeletedAt, Default } from 'sequelize-typescript';
import { Category } from 'src/category/category.model';
import { Product } from 'src/product/product.model';

@Table({
    timestamps: true,
    paranoid: true,
    tableName: 'discounts'
})
export class Discount extends Model<Discount> {
    //main primary key
    //generated by system
    @PrimaryKey
    @AutoIncrement
    @Column
    id: number;

    @Column
    title: string;
    
    @Column
    value: number;

    //created at datetime
    @CreatedAt
    created_at: Date;

    //updated at datetime
    @UpdatedAt
    updated_at: Date;

    //deleted at datetime
    @DeletedAt
    deleted_at: Date;

    @HasOne( () => Product)
    product: Product;

    @HasOne( () => Category)
    category: Category;
}