import { Column, Model, Table, HasOne, HasMany, DataType, PrimaryKey, AutoIncrement, Unique, ForeignKey, CreatedAt, UpdatedAt, DeletedAt, Default } from 'sequelize-typescript';

@Table({
    timestamps: true,
    paranoid: true,
    tableName: 'users'
})
export class User extends Model<User> {
    //main primary key
    //generated by system
    @PrimaryKey
    @AutoIncrement
    @Column
    id: number;

    @Column
    firstName: string;

    @Column
    lastName: string;

    @Column
    isActive: boolean;

    //created at datetime
    @CreatedAt
    created_at: Date;

    //updated at datetime
    @UpdatedAt
    updated_at: Date;

    //deleted at datetime
    @DeletedAt
    deleted_at: Date;
}