import { Column, Model, Table, HasOne, HasMany, DataType, PrimaryKey, AutoIncrement, Unique, ForeignKey, CreatedAt, UpdatedAt, DeletedAt, Default, BelongsTo } from 'sequelize-typescript';
import { Category } from 'src/category/category.model';
import { Discount } from 'src/discount/discount.model';

@Table({
    timestamps: true,
    paranoid: true,
    tableName: 'products'
})
export class Product extends Model<Product> {
    //main primary key
    //generated by system
    @PrimaryKey
    @AutoIncrement
    @Column
    id: number;

    
    //foreign key of wallet entity
    @ForeignKey(() => Category)
    @Column
    category_id: number;

    @BelongsTo( () => Category)
    category: Category;

    @BelongsTo( () => Discount)
    discount: Discount;

    //foreign key of wallet entity
    @ForeignKey(() => Discount)
    @Column
    discount_id: number;

    @Column
    title: string;

    @Column
    price: string;

    //created at datetime
    @CreatedAt
    created_at: Date;

    //updated at datetime
    @UpdatedAt
    updated_at: Date;

    //deleted at datetime
    @DeletedAt
    deleted_at: Date;
}